-- Create activity type enum
DO $$ BEGIN
    CREATE TYPE empties_activity_type AS ENUM (
      'customer_empties_return',
      'empties_to_supplier',
      'customer_purchase'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create empties_log table
CREATE TABLE IF NOT EXISTS empties_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  total_quantity INTEGER NOT NULL DEFAULT 0,
  activity empties_activity_type NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create empties_log_detail table
CREATE TABLE IF NOT EXISTS empties_log_detail (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_id BIGINT REFERENCES empties_log(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS Policies
ALTER TABLE empties_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE empties_log_detail ENABLE ROW LEVEL SECURITY;

-- Allow public access (matching existing patterns in the project)
DROP POLICY IF EXISTS "Allow public access" ON empties_log;
CREATE POLICY "Allow public access" ON empties_log FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public access" ON empties_log_detail;
CREATE POLICY "Allow public access" ON empties_log_detail FOR ALL USING (true);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS set_updated_at_empties_log ON empties_log;
CREATE TRIGGER set_updated_at_empties_log
BEFORE UPDATE ON empties_log
FOR EACH ROW
EXECUTE FUNCTION handle_updated_at();
