-- Create the products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  sku_name TEXT NOT NULL,
  returnable BOOLEAN NOT NULL DEFAULT FALSE,
  code_name TEXT,
  wholesale_price DECIMAL(10, 2),
  retail_price DECIMAL(10, 2)
);

-- Basic RLS policies (optional but recommended)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
CREATE POLICY "Allow public read access" ON products
  FOR SELECT USING (true);

-- Allow authenticated users (or service role) to insert/update/delete
-- Since we are using anon key for import script which might need insert access if RLS is on,
-- we either need to turn off RLS or add a policy for anon insert (not recommended for prod)
-- OR just tell the user to run the script.
-- ACTUALLY: The user provided ANON key. Anon key cannot insert if RLS is enabled and no policy allows it.
-- For the import script to work with ANON key, we need a policy allowing INSERT for anon, OR we tell the user to disable RLS for now.

-- Let's create a policy ensuring we can insert data.
-- Since this is an internal tool usage initially, let's allow inserts for now, OR better, 
-- we will just instruct the user to run the script.
-- Wait, I will use the anon key in the script.
-- Does the user have a logged in user? No.
-- So I should just DISABLE RLS for the import or add an INSERT policy for anon.
-- Let's add an insert policy for public for now to ease the import, then they can remove it.

CREATE POLICY "Allow public insert" ON products
  FOR INSERT WITH CHECK (true);
