-- Create inventory_log_type enum
DO $$ BEGIN
    CREATE TYPE inventory_log_type AS ENUM (
        'supplier_receipt',
        'vse_loadout',
        'retail_sale',
        'wholesale_sale',
        'breakage',
        'promo_out',
        'promo_reimbursement',
        'opening_stock'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create inventory_logs table
CREATE TABLE IF NOT EXISTS inventory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    product_id BIGINT REFERENCES products(id) NOT NULL,
    type inventory_log_type NOT NULL,
    quantity INTEGER NOT NULL, -- Positive for IN, Negative for OUT
    reference_id BIGINT,
    reference_table TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS Policies
ALTER TABLE inventory_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON inventory_logs FOR ALL USING (true);
