-- Table for tracking breakages in the warehouse
CREATE TABLE IF NOT EXISTS breakages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    product_id BIGINT REFERENCES products(id) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS Policies
ALTER TABLE breakages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON breakages FOR ALL USING (true);

-- Trigger to update warehouse_stock automatically when breakages are recorded
CREATE OR REPLACE FUNCTION update_stock_after_breakage()
RETURNS TRIGGER AS $$
BEGIN
    -- Update stock
    INSERT INTO warehouse_stock (product_id, quantity)
    VALUES (NEW.product_id, -NEW.quantity)
    ON CONFLICT (product_id)
    DO UPDATE SET 
        quantity = warehouse_stock.quantity - EXCLUDED.quantity,
        updated_at = NOW();

    -- Log movement
    INSERT INTO inventory_logs (product_id, type, quantity, reference_id, reference_table, description)
    VALUES (NEW.product_id, 'breakage', -NEW.quantity, NEW.id, 'breakages', NEW.reason);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_stock_after_breakage
AFTER INSERT ON breakages
FOR EACH ROW
EXECUTE FUNCTION update_stock_after_breakage();
