-- Create warehouse_order_status enum
DO $$ BEGIN
    CREATE TYPE warehouse_order_status AS ENUM ('pending', 'ready', 'cancelled');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 1. Create warehouse_orders table
CREATE TABLE IF NOT EXISTS warehouse_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    status warehouse_order_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create warehouse_order_items table
CREATE TABLE IF NOT EXISTS warehouse_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_order_id BIGINT REFERENCES warehouse_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    quantity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Trigger for updated_at on warehouse_orders
CREATE TRIGGER set_updated_at_warehouse_orders
BEFORE UPDATE ON warehouse_orders
FOR EACH ROW
EXECUTE FUNCTION handle_updated_at();

-- RLS Policies
ALTER TABLE warehouse_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE warehouse_order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access" ON warehouse_orders FOR ALL USING (true);
CREATE POLICY "Allow public access" ON warehouse_order_items FOR ALL USING (true);
