-- Create loadouts and loadout_items tables
CREATE TABLE IF NOT EXISTS loadouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    vse_id BIGINT REFERENCES customers(id) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS loadout_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loadout_id BIGINT REFERENCES loadouts(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES products(id) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS Policies
ALTER TABLE loadouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE loadout_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access" ON loadouts FOR ALL USING (true);
CREATE POLICY "Allow public access" ON loadout_items FOR ALL USING (true);

-- Trigger for updated_at on loadouts
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_loadouts
BEFORE UPDATE ON loadouts
FOR EACH ROW
EXECUTE FUNCTION handle_updated_at();
